#!/bin/bash

c=$'\033[0;36m' # cyan
b=$'\033[0;34m' # blue
y=$'\033[0;33m' # yellow
r=$'\033[0m'    # reset

function print_help {
  cat <<EOF
${c}fc-dᵾmp${r} - Font character map extractor

${y}Usage:${r}
  fc-dump ${b}<file>${r}

${y}Arguments:${r}
  ${b}file${r}  Font file (ttf/otf/ttx)

${y}Examples:${r}
  fc-dump font.ttf     ${c}# process ttf file${r}
  fc-dump font.otf     ${c}# process otf file${r}
  fc-dump font.ttx     ${c}# process ttx file${r}

${y}Find Fonts:${r}
  fc-list
  ls /usr/share/fonts
EOF
}

case $1 in
*.ttx) ttx=$1 ;;
-h | --help) print_help ;;
*.ttf | *.otf)
  ttx="$(basename "${1%.*}.ttx")"
  [[ ! -f $ttx ]] && ttx -o "$ttx" "$1"
  ;;
*)
  print_help
  exit 1
  ;;
esac

sed -E -n 's/.*<map code="([^"]*)".*/\1/p' "$ttx" |
  tr -d '\r' |
  awk '{printf("%c ", strtonum($1))}'

echo

# vim: set ft=sh:
